env:
  node: true
  es2020: true

extends:
  - airbnb-base
  - plugin:prettier/recommended

plugins:
  - simple-import-sort

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: off
  import/extensions: off
  no-underscore-dangle: [error, { allow: ["__filename", "__dirname"] }]
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  sort-imports: off
  import/order: off
